Repository clingen-data-model/architecture, pull requests merged in 2021-09, with the labels that each got.

#127 bumping docker image for genegraph
  helm/values/genegraph/values-dev.yaml
Labels: automation

#128 bumping docker image for genegraph
  helm/values/genegraph/values-dev.yaml
Labels: automation

#129 bumping docker image for genegraph
  helm/values/genegraph/values-dev.yaml
Labels: automation

#132 bumping docker image for genegraph
  helm/values/genegraph/values-dev.yaml
Labels: automation

#134 bumping docker image for clinvar-submitter
  helm/values/clinvar-submitter/values-prod.yaml
  helm/values/clinvar-submitter/values-stage.yaml
Labels: automation

#72 Automated deploy of clinvar streams
  helm/charts/clinvar-combined-stream/.helmignore
  helm/charts/clinvar-combined-stream/Chart.yaml
  helm/charts/clinvar-combined-stream/pre-deploy-script.sh
  helm/charts/clinvar-combined-stream/templates/_helpers.tpl
  helm/charts/clinvar-combined-stream/templates/clinvar-combiner-statefulset.yaml
  helm/charts/clinvar-combined-stream/templates/secret.yaml
  helm/charts/clinvar-combined-stream/templates/service.yaml
  helm/charts/clinvar-combined-stream/templates/storageclass.yaml
  helm/charts/clinvar-combined-stream/values.yaml
  helm/charts/clinvar-raw-stream/.helmignore
  helm/charts/clinvar-raw-stream/Chart.yaml
  helm/charts/clinvar-raw-stream/README.md
  helm/charts/clinvar-raw-stream/templates/_helpers.tpl
  helm/charts/clinvar-raw-stream/templates/clinvar-raw-statefulset.yaml
  helm/charts/clinvar-raw-stream/templates/secret.yaml
  helm/charts/clinvar-raw-stream/templates/service.yaml
  helm/charts/clinvar-raw-stream/values.yaml
  helm/cloudbuild.yaml
  helm/helmfile.d/dev.yaml
  helm/values/clinvar-combined-stream/values-dev.yaml
  helm/values/clinvar-raw-stream/values-dev.yaml
  helm/values/genegraph-clinvar/values-dev.yaml
Labels: clinvar

#136 vendor our own cloudarmor module
  helm/charts/clingen-argocd/templates/argocd-backendconfig.yaml
  terraform/prod/argo.tf
Labels: sre

#139 Lock the terraform version
  terraform/dev/remote_state.tf
  terraform/prod/remote_state.tf
  terraform/shared/iam/remote_state.tf
  terraform/stage/remote_state.tf
Labels: sre

#140 bumping docker image for clinvar-submitter
  helm/values/clinvar-submitter/values-prod.yaml
  helm/values/clinvar-submitter/values-stage.yaml
Labels: automation
